import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  guides: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  projects: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
  ],
  copilot: [
    {
      type: 'autogenerated',
      dirName: 'copilot',
    },
  ],
};
export default sidebars;