import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  guides: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  projects: [
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          type: 'link',
          label: 'Overview',
          href: '/projects',
        },
        {
          type: 'autogenerated',
          dirName: 'projects',
        },
      ],
    },
  ],
};
export default sidebars;