name: 'Hello World Composite Action'
description: 'A simple composite action example'
inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
  greeting:
    description: 'Greeting to use'
    required: false
    default: 'Hello'
outputs:
  response:
    description: 'The greeting response'
    value: ${{ steps.greet.outputs.response }}
runs:
  using: 'composite'
  steps:
    - name: Greet
      id: greet
      shell: bash
      run: |
        echo "response=${{ inputs.greeting }}, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
        echo "${{ inputs.greeting }}, ${{ inputs.name }}! 👋"
