name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ESLint and SARIF formatter
        shell: bash
        run: |
          npm i eslint@^8.9.0
          npm i @microsoft/eslint-formatter-sarif
      - name: Run ESLint
        shell: bash
        run: npm run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        continue-on-error: true
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true